services:
  fast_api:
    build: .
    container_name: ubigeo_ven
    init: true
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - type: bind
        source: .
        target: /code
    working_dir: /code
    healthcheck:
      test: curl --fail http://localhost:5000/v1/health || exit 1
      interval: 10m
      timeout: 5s